on:
  push:
    branches:
      - main

jobs:
  collect-example:
    runs-on: ubuntu-latest
    env:
      BUILDNOTE_API_KEY: ${{ secrets.BUILDNOTE_API_KEY }}
      BUILDNOTE_GITHUB_JOB_NAME: collect-example
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.7

      - name: Collect
        uses: buildnote/action@main
        with:
          args: "--include-junit-test-results=**/TEST-junit*.xml"
